### ISSUE TITLE
Noise variance and thermal noise models

### ISSUE THREAD

**Issue by mkolopanis** [mkolopanis/simpleDS#8]
simulated noise inside of the module does not produce noise variance which agrees with 21cmsense_calc thermal noise expectations. see the attached image. The dashed lines (noise simulation variance) disagrees with the thermal variance(21cmsense_calc) by up to a factor of 2. Also appears to have some frequency dependence:
![figure 23](https://user-images.githubusercontent.com/8646829/45905102-0b7fa100-bda4-11e8-91a9-8c1e8b109423.png)

**Comment by mkolopanis** [comment]
There was an improper normalization of the noise power spectrum before. It didn't not have a factor of `uvb.get_beam_area()**2` adding this factor gives:
![image](https://user-images.githubusercontent.com/8646829/46094895-063da000-c170-11e8-84e6-99972610c524.png)

The error bars now systematically underestimate the thermal prediction by a factor of 2. This could be from the introduction of the `npols` in the noise_power calculation inside simpleDS

**Comment by mkolopanis** [comment]
This is a comparison of the time averaged spectrum of an input noise file for PAPER. trcvr=144k versus the built in noise simulation 
![image](https://user-images.githubusercontent.com/8646829/46095936-aac0e180-c172-11e8-83ac-b207016acaa2.png)

**Comment by dannyjacobs** [comment]
Where exactly was the beam squared missing? Can you point to the lines of code involved?

**Comment by mkolopanis** [comment]
https://github.com/mkolopanis/simpleDS/blob/89d8b291e333f3a83b3b75a96600886aa97c1d8b/simpleDS/delay_spectrum.py#L277-L278
these lines used to read as :
   ``` 
    even_noise = generate_noise(even_noise)  / np.sqrt(uvb.get_beam_sq_area())
    odd_noise = generate_noise(odd_noise) / np.sqrt(uvb.get_beam_sq_area())
```
but the addition of the `uvb.get_beam_area()` provides what I am beginning to believe is the proper normalization. I also am not partiularly happy with how the normalization is implemented right now (sqrts is a nasty thing sometimes) so it may move around. I will update this issue to link to the correct lines if that happens.

**Comment by dannyjacobs** [comment]
Yeah agreed about sqrts and denominators. Also we should prefer well defined variables or functions like mKperJy or mK2perJy.
